inherit_from:
- .rubocop_airbnb.yml

Rails:
  Enabled: true

LineLength:
  Max: 130

Airbnb/RiskyActiverecordInvocation:
  Exclude:
    - 'app/controllers/employees_controller.rb'

Rails/UniqueValidationWithoutIndex:
  Exclude:
    - 'app/models/employee.rb'

AllCops:
  Exclude:
    - 'db/**/*'
    - 'bin/*'
    - 'config/environments/*'
    - 'config/application.rb'
    - 'config/initializers/*'
    - 'config/spring.rb'
    - 'lib/tasks/*'
    - 'vendor/**/*'
    - 'path/ruby'
